#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Video {
    _1DInterleavedParityfec,
    _3Gpp,
    _3Gpp2,
    _3GppTt,
    Av1,
    Bmpeg,
    Bt656,
    CelB,
    Dv,
    Encaprtp,
    Example,
    Ffv1,
    Flexfec,
    H261,
    H263,
    H2631998,
    H2632000,
    H264,
    H264Rcdo,
    H264Svc,
    H265,
    H266,
    IsoSegment,
    Jpeg,
    Jpeg2000,
    Jxsv,
    Mj2,
    Mp1S,
    Mp2P,
    Mp2T,
    Mp4,
    Mp4VEs,
    Mpv,
    Mpeg4Generic,
    Nv,
    Ogg,
    Parityfec,
    Pointer,
    Quicktime,
    Raptorfec,
    Raw,
    RtpEncAescm128,
    Rtploopback,
    Rtx,
    Scip,
    Smpte291,
    Smpte292M,
    Ulpfec,
    Vc1,
    Vc2,
    VndCCTV,
    VndDeceHd,
    VndDeceMobile,
    VndDeceMp4,
    VndDecePd,
    VndDeceSd,
    VndDeceVideo,
    VndDirectvMpeg,
    VndDirectvMpegTts,
    VndDlnaMpegTts,
    VndDvbFile,
    VndFvt,
    VndHnsVideo,
    VndIptvforum1Dparityfec1010,
    VndIptvforum1Dparityfec2005,
    VndIptvforum2Dparityfec1010,
    VndIptvforum2Dparityfec2005,
    VndIptvforumTtsavc,
    VndIptvforumTtsmpeg2,
    VndMotorolaVideo,
    VndMotorolaVideop,
    VndMpegurl,
    VndMsPlayreadyMediaPyv,
    VndNokiaInterleavedMultimedia,
    VndNokiaMp4Vr,
    VndNokiaVideovoip,
    VndObjectvideo,
    VndRadgamettoolsBink,
    VndRadgamettoolsSmacker,
    VndSealedMpeg1,
    VndSealedMpeg4,
    VndSealedSwf,
    VndSealedmediaSoftsealMov,
    VndUvvuMp4,
    VndYoutubeYt,
    VndVivo,
    Vp8,
    Vp9,
    Other(String),
}
impl ::std::fmt::Display for Video {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Video::_1DInterleavedParityfec => write!(f, "video/1d-interleaved-parityfec")?,
            Video::_3Gpp => write!(f, "video/3gpp")?,
            Video::_3Gpp2 => write!(f, "video/3gpp2")?,
            Video::_3GppTt => write!(f, "video/3gpp-tt")?,
            Video::Av1 => write!(f, "video/AV1")?,
            Video::Bmpeg => write!(f, "video/BMPEG")?,
            Video::Bt656 => write!(f, "video/BT656")?,
            Video::CelB => write!(f, "video/CelB")?,
            Video::Dv => write!(f, "video/DV")?,
            Video::Encaprtp => write!(f, "video/encaprtp")?,
            Video::Example => write!(f, "video/example")?,
            Video::Ffv1 => write!(f, "video/FFV1")?,
            Video::Flexfec => write!(f, "video/flexfec")?,
            Video::H261 => write!(f, "video/H261")?,
            Video::H263 => write!(f, "video/H263")?,
            Video::H2631998 => write!(f, "video/H263-1998")?,
            Video::H2632000 => write!(f, "video/H263-2000")?,
            Video::H264 => write!(f, "video/H264")?,
            Video::H264Rcdo => write!(f, "video/H264-RCDO")?,
            Video::H264Svc => write!(f, "video/H264-SVC")?,
            Video::H265 => write!(f, "video/H265")?,
            Video::H266 => write!(f, "video/H266")?,
            Video::IsoSegment => write!(f, "video/iso.segment")?,
            Video::Jpeg => write!(f, "video/JPEG")?,
            Video::Jpeg2000 => write!(f, "video/jpeg2000")?,
            Video::Jxsv => write!(f, "video/jxsv")?,
            Video::Mj2 => write!(f, "video/mj2")?,
            Video::Mp1S => write!(f, "video/MP1S")?,
            Video::Mp2P => write!(f, "video/MP2P")?,
            Video::Mp2T => write!(f, "video/MP2T")?,
            Video::Mp4 => write!(f, "video/mp4")?,
            Video::Mp4VEs => write!(f, "video/MP4V-ES")?,
            Video::Mpv => write!(f, "video/MPV")?,
            Video::Mpeg4Generic => write!(f, "video/mpeg4-generic")?,
            Video::Nv => write!(f, "video/nv")?,
            Video::Ogg => write!(f, "video/ogg")?,
            Video::Parityfec => write!(f, "video/parityfec")?,
            Video::Pointer => write!(f, "video/pointer")?,
            Video::Quicktime => write!(f, "video/quicktime")?,
            Video::Raptorfec => write!(f, "video/raptorfec")?,
            Video::Raw => write!(f, "video/raw")?,
            Video::RtpEncAescm128 => write!(f, "video/rtp-enc-aescm128")?,
            Video::Rtploopback => write!(f, "video/rtploopback")?,
            Video::Rtx => write!(f, "video/rtx")?,
            Video::Scip => write!(f, "video/scip")?,
            Video::Smpte291 => write!(f, "video/smpte291")?,
            Video::Smpte292M => write!(f, "video/SMPTE292M")?,
            Video::Ulpfec => write!(f, "video/ulpfec")?,
            Video::Vc1 => write!(f, "video/vc1")?,
            Video::Vc2 => write!(f, "video/vc2")?,
            Video::VndCCTV => write!(f, "video/vnd.CCTV")?,
            Video::VndDeceHd => write!(f, "video/vnd.dece.hd")?,
            Video::VndDeceMobile => write!(f, "video/vnd.dece.mobile")?,
            Video::VndDeceMp4 => write!(f, "video/vnd.dece.mp4")?,
            Video::VndDecePd => write!(f, "video/vnd.dece.pd")?,
            Video::VndDeceSd => write!(f, "video/vnd.dece.sd")?,
            Video::VndDeceVideo => write!(f, "video/vnd.dece.video")?,
            Video::VndDirectvMpeg => write!(f, "video/vnd.directv.mpeg")?,
            Video::VndDirectvMpegTts => write!(f, "video/vnd.directv.mpeg-tts")?,
            Video::VndDlnaMpegTts => write!(f, "video/vnd.dlna.mpeg-tts")?,
            Video::VndDvbFile => write!(f, "video/vnd.dvb.file")?,
            Video::VndFvt => write!(f, "video/vnd.fvt")?,
            Video::VndHnsVideo => write!(f, "video/vnd.hns.video")?,
            Video::VndIptvforum1Dparityfec1010 => {
                write!(f, "video/vnd.iptvforum.1dparityfec-1010")?
            }
            Video::VndIptvforum1Dparityfec2005 => {
                write!(f, "video/vnd.iptvforum.1dparityfec-2005")?
            }
            Video::VndIptvforum2Dparityfec1010 => {
                write!(f, "video/vnd.iptvforum.2dparityfec-1010")?
            }
            Video::VndIptvforum2Dparityfec2005 => {
                write!(f, "video/vnd.iptvforum.2dparityfec-2005")?
            }
            Video::VndIptvforumTtsavc => write!(f, "video/vnd.iptvforum.ttsavc")?,
            Video::VndIptvforumTtsmpeg2 => write!(f, "video/vnd.iptvforum.ttsmpeg2")?,
            Video::VndMotorolaVideo => write!(f, "video/vnd.motorola.video")?,
            Video::VndMotorolaVideop => write!(f, "video/vnd.motorola.videop")?,
            Video::VndMpegurl => write!(f, "video/vnd.mpegurl")?,
            Video::VndMsPlayreadyMediaPyv => write!(f, "video/vnd.ms-playready.media.pyv")?,
            Video::VndNokiaInterleavedMultimedia => {
                write!(f, "video/vnd.nokia.interleaved-multimedia")?
            }
            Video::VndNokiaMp4Vr => write!(f, "video/vnd.nokia.mp4vr")?,
            Video::VndNokiaVideovoip => write!(f, "video/vnd.nokia.videovoip")?,
            Video::VndObjectvideo => write!(f, "video/vnd.objectvideo")?,
            Video::VndRadgamettoolsBink => write!(f, "video/vnd.radgamettools.bink")?,
            Video::VndRadgamettoolsSmacker => write!(f, "video/vnd.radgamettools.smacker")?,
            Video::VndSealedMpeg1 => write!(f, "video/vnd.sealed.mpeg1")?,
            Video::VndSealedMpeg4 => write!(f, "video/vnd.sealed.mpeg4")?,
            Video::VndSealedSwf => write!(f, "video/vnd.sealed.swf")?,
            Video::VndSealedmediaSoftsealMov => write!(f, "video/vnd.sealedmedia.softseal.mov")?,
            Video::VndUvvuMp4 => write!(f, "video/vnd.uvvu.mp4")?,
            Video::VndYoutubeYt => write!(f, "video/vnd.youtube.yt")?,
            Video::VndVivo => write!(f, "video/vnd.vivo")?,
            Video::Vp8 => write!(f, "video/VP8")?,
            Video::Vp9 => write!(f, "video/VP9")?,
            Video::Other(template) => write!(f, "{}", template)?,
        }
        Ok(())
    }
}
impl From<&str> for Video {
    fn from(input: &str) -> Self {
        match input {
            "video/1d-interleaved-parityfec" => Video::_1DInterleavedParityfec,
            "video/3gpp" => Video::_3Gpp,
            "video/3gpp2" => Video::_3Gpp2,
            "video/3gpp-tt" => Video::_3GppTt,
            "video/AV1" => Video::Av1,
            "video/BMPEG" => Video::Bmpeg,
            "video/BT656" => Video::Bt656,
            "video/CelB" => Video::CelB,
            "video/DV" => Video::Dv,
            "video/encaprtp" => Video::Encaprtp,
            "video/example" => Video::Example,
            "video/FFV1" => Video::Ffv1,
            "video/flexfec" => Video::Flexfec,
            "video/H261" => Video::H261,
            "video/H263" => Video::H263,
            "video/H263-1998" => Video::H2631998,
            "video/H263-2000" => Video::H2632000,
            "video/H264" => Video::H264,
            "video/H264-RCDO" => Video::H264Rcdo,
            "video/H264-SVC" => Video::H264Svc,
            "video/H265" => Video::H265,
            "video/H266" => Video::H266,
            "video/iso.segment" => Video::IsoSegment,
            "video/JPEG" => Video::Jpeg,
            "video/jpeg2000" => Video::Jpeg2000,
            "video/jxsv" => Video::Jxsv,
            "video/mj2" => Video::Mj2,
            "video/MP1S" => Video::Mp1S,
            "video/MP2P" => Video::Mp2P,
            "video/MP2T" => Video::Mp2T,
            "video/mp4" => Video::Mp4,
            "video/MP4V-ES" => Video::Mp4VEs,
            "video/MPV" => Video::Mpv,
            "video/mpeg4-generic" => Video::Mpeg4Generic,
            "video/nv" => Video::Nv,
            "video/ogg" => Video::Ogg,
            "video/parityfec" => Video::Parityfec,
            "video/pointer" => Video::Pointer,
            "video/quicktime" => Video::Quicktime,
            "video/raptorfec" => Video::Raptorfec,
            "video/raw" => Video::Raw,
            "video/rtp-enc-aescm128" => Video::RtpEncAescm128,
            "video/rtploopback" => Video::Rtploopback,
            "video/rtx" => Video::Rtx,
            "video/scip" => Video::Scip,
            "video/smpte291" => Video::Smpte291,
            "video/SMPTE292M" => Video::Smpte292M,
            "video/ulpfec" => Video::Ulpfec,
            "video/vc1" => Video::Vc1,
            "video/vc2" => Video::Vc2,
            "video/vnd.CCTV" => Video::VndCCTV,
            "video/vnd.dece.hd" => Video::VndDeceHd,
            "video/vnd.dece.mobile" => Video::VndDeceMobile,
            "video/vnd.dece.mp4" => Video::VndDeceMp4,
            "video/vnd.dece.pd" => Video::VndDecePd,
            "video/vnd.dece.sd" => Video::VndDeceSd,
            "video/vnd.dece.video" => Video::VndDeceVideo,
            "video/vnd.directv.mpeg" => Video::VndDirectvMpeg,
            "video/vnd.directv.mpeg-tts" => Video::VndDirectvMpegTts,
            "video/vnd.dlna.mpeg-tts" => Video::VndDlnaMpegTts,
            "video/vnd.dvb.file" => Video::VndDvbFile,
            "video/vnd.fvt" => Video::VndFvt,
            "video/vnd.hns.video" => Video::VndHnsVideo,
            "video/vnd.iptvforum.1dparityfec-1010" => Video::VndIptvforum1Dparityfec1010,
            "video/vnd.iptvforum.1dparityfec-2005" => Video::VndIptvforum1Dparityfec2005,
            "video/vnd.iptvforum.2dparityfec-1010" => Video::VndIptvforum2Dparityfec1010,
            "video/vnd.iptvforum.2dparityfec-2005" => Video::VndIptvforum2Dparityfec2005,
            "video/vnd.iptvforum.ttsavc" => Video::VndIptvforumTtsavc,
            "video/vnd.iptvforum.ttsmpeg2" => Video::VndIptvforumTtsmpeg2,
            "video/vnd.motorola.video" => Video::VndMotorolaVideo,
            "video/vnd.motorola.videop" => Video::VndMotorolaVideop,
            "video/vnd.mpegurl" => Video::VndMpegurl,
            "video/vnd.ms-playready.media.pyv" => Video::VndMsPlayreadyMediaPyv,
            "video/vnd.nokia.interleaved-multimedia" => Video::VndNokiaInterleavedMultimedia,
            "video/vnd.nokia.mp4vr" => Video::VndNokiaMp4Vr,
            "video/vnd.nokia.videovoip" => Video::VndNokiaVideovoip,
            "video/vnd.objectvideo" => Video::VndObjectvideo,
            "video/vnd.radgamettools.bink" => Video::VndRadgamettoolsBink,
            "video/vnd.radgamettools.smacker" => Video::VndRadgamettoolsSmacker,
            "video/vnd.sealed.mpeg1" => Video::VndSealedMpeg1,
            "video/vnd.sealed.mpeg4" => Video::VndSealedMpeg4,
            "video/vnd.sealed.swf" => Video::VndSealedSwf,
            "video/vnd.sealedmedia.softseal.mov" => Video::VndSealedmediaSoftsealMov,
            "video/vnd.uvvu.mp4" => Video::VndUvvuMp4,
            "video/vnd.youtube.yt" => Video::VndYoutubeYt,
            "video/vnd.vivo" => Video::VndVivo,
            "video/VP8" => Video::Vp8,
            "video/VP9" => Video::Vp9,
            _ => Video::Other(input.to_string()),
        }
    }
}
